export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGINADMIN_SUCCESS = "LOGINADMIN_SUCCESS"
export const LOGINUSER_SUCCESS = "LOGINUSER_SUCCESS"
export const CLEAR_REDUX_STATE = "CLEAR_REDUX_STATE"


export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const SOCIAL_LOGIN = "SOCIAL_LOGIN"
